web/front/urls.py
from django.conf.urls import url

from front import views

urlpatterns = [
    url(r'^user/$', views.user, name='user'),
    url(r'^player/add/$', views.player_add, name='player_add'),
    url(r'^player/(?P<id>[0-9]+)/$', views.player, name='player'),
    url(r'^result/(?P<id>[0-9]+)/$', views.result, name='result'),
    url(r'^player/(?P<id>[0-9]+)/enable/$', views.player_enable, name='player_enable'),
    url(r'^player/(?P<id>[0-9]+)/disable/$', views.player_disable, name='player_disable'),
    url(r'^player/(?P<id>[0-9]+)/delete/$', views.player_delete, name='player_delete'),
    url(r'^round/(?P<id>[0-9]+)/$', views.round, name='round'),
    url(r'^$', views.rounds, name='rounds'),
]

web/spectrumwarsweb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

import registration.backends.simple.urls
import front.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include(registration.backends.simple.urls)),
    url(r'^', include(front.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/front/models.py
import ast
from django.db import models
from django.contrib.auth.models import User
from django import forms

def check_syntax(code):
	try:
		ast.parse(code, '<string>', 'exec')
	except Exception, e:
		raise forms.ValidationError("SyntaxError: %s" %(e,))

class Player(models.Model):
	user = models.ForeignKey(User)
	name = models.CharField(max_length=255, unique=True)
	code = models.TextField(validators=[check_syntax])
	created = models.DateTimeField(auto_now_add=True)
	enabled = models.BooleanField()
	in_use = models.BooleanField(default=True)

	def __unicode__(self):
		return self.name

class Round(models.Model):
	started = models.DateTimeField(auto_now_add=True)

	start_time = models.DateTimeField()
	finish_time = models.DateTimeField(null=True)

	nplayers = models.IntegerField()
	testbed = models.CharField(max_length=255)

	state = models.CharField(max_length=255)

	def __unicode__(self):
		return "Round %d" % (self.id,)

class Game(models.Model):
	duration = models.FloatField()
	ran = models.DateTimeField(auto_now_add=True)
	round = models.ForeignKey(Round)

	timeline = models.FileField(upload_to="timeline")

class PlayerResult(models.Model):
	game = models.ForeignKey(Game)
	player = models.ForeignKey(Player)

	transmit_packets = models.IntegerField()
	received_packets = models.IntegerField()

	payload_bytes = models.IntegerField()

	crashed = models.BooleanField()
	log = models.TextField()
	timeline = models.FileField(upload_to="timeline")

	def get_packet_loss(self):

		if self.transmit_packets > 0.:
			return 100. * (self.transmit_packets - self.received_packets) / self.transmit_packets
		else:
			return float("NaN")

	def get_throughput(self):

		duration = self.game.duration
		if duration > 0.:
			return self.payload_bytes / duration
		else:
			return float("NaN")

web/front/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django import forms
from django.core.exceptions import PermissionDenied
from django.db import transaction

from front.models import Player, PlayerResult, Round, Game
import math

class PlayerForm(forms.ModelForm):
	class Meta:
		model = Player
		fields = ['name', 'code']
		widgets = {
			'code': forms.Textarea(attrs={'cols': 80, 'rows': 20}),
		}

@login_required
def user(request):
	player_list = Player.objects.filter(user=request.user)

	for player in player_list:
		result_list = PlayerResult.objects.filter(player=player)

		packet_loss = []
		crash = []

		for result in result_list:
			crash.append(int(result.crashed)*100)

			pl = result.get_packet_loss()

			if not math.isnan(pl):
				packet_loss.append(pl)

		player.crash_ratio = get_mean(crash)
		player.packet_loss = get_mean(packet_loss)

	player_list_sorted = sorted(player_list, key=lambda x:(not x.enabled, x.crash_ratio, x.packet_loss))

	context = {
		'user': request.user,
		'player_list': player_list_sorted,
	}

	return render(request, 'front/user.html', context)

@login_required
def player_add(request):
	if request.method == 'POST':
		form = PlayerForm(request.POST)
		if form.is_valid():

			p = Player(	user=request.user,
					name=form.cleaned_data['name'],
					code=form.cleaned_data['code'],
					enabled=True,
					in_use=False)
			p.save()

			return HttpResponseRedirect(reverse('user'))
	else:
		form = PlayerForm()

	context = { 'form': form }

	return render(request, 'front/player_add.html', context)

@login_required
def player(request, id):
	player = get_object_or_404(Player, pk=id)

	if player.user != request.user:
		raise PermissionDenied

	result_list = PlayerResult.objects.filter(player=player)

	context = {
		'player': player,
		'result_list': result_list,
		'user': request.user,
	}

	return render(request, 'front/player.html', context)

@login_required
def player_enable(request, id):
	player = get_object_or_404(Player, pk=id)

	if player.user != request.user:
		raise PermissionDenied

	if request.method == 'POST':
		player.enabled = True
		player.save()

	return HttpResponseRedirect(reverse('player', args=(id,)))

@login_required
def player_disable(request, id):
	player = get_object_or_404(Player, pk=id)

	if player.user != request.user:
		raise PermissionDenied

	if request.method == 'POST':
		player.enabled = False
		player.save()

	return HttpResponseRedirect(reverse('player', args=(id,)))

@login_required
def player_delete(request, id):
	player = get_object_or_404(Player, pk=id)

	if player.user != request.user:
		raise PermissionDenied

	with transaction.atomic():
		if player.in_use:
			raise PermissionDenied

		if request.method == 'POST':
			player.delete()

	return HttpResponseRedirect(reverse('user'))

@login_required
def result(request, id):
	result = get_object_or_404(PlayerResult, pk=id)

	if result.player.user != request.user:
		raise PermissionDenied

	context = {
		'result': result,
	}

	return render(request, 'front/result.html', context)

def rounds(request):

	round_list = []

	for round in Round.objects.all():

		game_list = Game.objects.filter(round=round)

		round.n_games = game_list.count()

		players = set()
		for result in PlayerResult.objects.filter(game__in=game_list):
			players.add(result.player.id)

		round.n_players = len(players)

		round_list.append(round)

	user_set = set()
	player_num = 0
	for player in Player.objects.filter(enabled=True):
		user_set.add(player.user.id)
		player_num += 1

	context = {
		'round_list': round_list,
		'player_num': player_num,
		'user_num': len(user_set),
	}

	return render(request, 'front/rounds.html', context)

def get_mean(x):

	if len(x) > 0:
		return float(sum(x))/len(x)
	else:
		return None

def get_max(x):
	if len(x) > 0:
		return max(x)
	else:
		return None

def get_min(x):
	if len(x) > 0:
		return min(x)
	else:
		return None

def round(request, id):
	round = get_object_or_404(Round, pk=id)
	game_list = Game.objects.filter(round=round)

	player_list = Player.objects.all()

	player_list2 = []
	for player in player_list:

		packet_loss = []
		throughput = []

		game_packet_loss = []
		other_packet_loss = []

		in_round = False

		for result in PlayerResult.objects.filter(player=player, game__in=game_list):

			in_round = True

			had_crash = False
			for result2 in PlayerResult.objects.filter(game=result.game):
				if result2.crashed:
					had_crash = True
					break
			if had_crash:
				continue

			for result2 in PlayerResult.objects.filter(game=result.game):

				game_packet_loss.append(result2.get_packet_loss())

				if result2.id != result.id:
					other_packet_loss.append(result2.get_packet_loss())

			packet_loss.append(result.get_packet_loss())
			throughput.append(result.get_throughput())

		player.avg_packet_loss = get_mean(packet_loss)
		player.max_packet_loss = get_max(packet_loss)
		player.avg_throughput = get_mean(throughput)
		player.min_throughput = get_min(throughput)
		player.game_packet_loss = get_mean(game_packet_loss)
		player.other_packet_loss = get_min(other_packet_loss)

		if in_round:
			player_list2.append(player)

	def do_sort(key, reverse=False):
		a = list(player_list2)
		a.sort(key=lambda x:getattr(x, key), reverse=reverse)
		a.sort(key=lambda x:getattr(x, key) == None)

		return a

	most_reliable = do_sort('max_packet_loss')
	fastest = do_sort('min_throughput', reverse=True)
	most_cooperative = do_sort('game_packet_loss')
	best_interferer = do_sort('other_packet_loss', reverse=True)

	context = {
		'round': round,
		'game_list': game_list,
		'most_reliable': most_reliable,
		'fastest': fastest,
		'most_cooperative': most_cooperative,
		'best_interferer': best_interferer,
	}

	return render(request, 'front/round.html', context)

web/front/templates/front/halloffame.html
{% extends "base.html" %}

{% block title %}
Ranking
{% endblock %}

{% block content %}
<h2>Most reliable</h2>

<table>
<tr>
<th>Name</th>
<th>Author</th>
<th>Packet loss</th>
</tr>
{% for player in most_reliable %}
<tr>
<td>"{{ player }}"</td>
<td>{{ player.user }}</td>
<td>{% if player.avg_packet_loss != None %}{{ player.avg_packet_loss|floatformat:"1" }} %{% endif %}</td>
</tr>
{% endfor %}
</table>

<h2>Fastest</h2>

<table>
<tr>
<th>Name</th>
<th>Author</th>
<th>Throughput</th>
</tr>
{% for player in fastest %}
<tr>
<td>"{{ player }}"</td>
<td>{{ player.user }}</td>
<td>{% if player.avg_throughput != None %}{{ player.avg_throughput|floatformat:"1" }} bytes/s{% endif %}</td>
</tr>
{% endfor %}
</table>

<h2>Most cooperative</h2>

<table>
<tr>
<th>Name</th>
<th>Author</th>
<th>Coop. packet loss</th>
</tr>
{% for player in most_cooperative %}
<tr>
<td>"{{ player }}"</td>
<td>{{ player.user }}</td>
<td>{% if player.game_packet_loss != None %}{{ player.game_packet_loss|floatformat:"1" }} %{% endif %}</td>
</tr>
{% endfor %}
</table>

<h2>Best interferer</h2>

<table>
<tr>
<th>Name</th>
<th>Author</th>
<th>Packet loss of others</th>
</tr>
{% for player in best_interferer %}
<tr>
<td>"{{ player }}"</td>
<td>{{ player.user }}</td>
<td>{% if player.other_packet_loss != None %}{{ player.other_packet_loss|floatformat:"1" }} %{% endif %}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

web/front/templates/front/index.html
{% extends "base.html" %}

{% block title %}
Hello {{ user }}!
{% endblock %}

{% block content %}

<p>Your players:</p>

<table>
<tr>
<th>name</th><th>crash<br/>ratio</th><th>packet loss</th><th>created</th>
{% for player in player_list %}
<tr>
<td><a href="/front/player/{{ player.id}}">{{ player.name }}</a></td>
<td>{{ player.crash_ratio|floatformat:"0" }} %</td>
<td>{% if player.packet_loss != None %}{{ player.packet_loss|floatformat:"1" }} %{% endif %}</td>
<td>{{ player.created }}</td>
</tr>
{% endfor %}
</table>

<p>
<a href="{% url 'player_add' %}">Submit a player</a>
</p>
<p>
<a href="{% url 'rounds' %}">Back</a>
</p>
<p>
<a href="{% url 'auth_logout' %}">Log out</a>
</p>
{% endblock %}

web/front/templates/front/player.html
{% extends "base.html" %}

{% block title %}
"{{ player.name }}" by {{ user }}
{% endblock %}

{% block content %}
{% if player.enabled %}
<form action="{% url 'player_disable' player.id %}" method="post">
	{% csrf_token %}
	<input type="submit" value="disable"/>
</form>
{% else %}
<form action="{% url 'player_enable' player.id %}" method="post">
	{% csrf_token %}
	<input type="submit" value="enable"/>
</form>
{% endif %}

<p>Disabling a player prevents it from participating in future rounds.</p>

<form action="{% url 'player_delete' player.id %}" method="post">
	{% csrf_token %}
	<input type="submit" value="delete" {% if player.in_use %}disabled{% endif %} />
</form>

<p>You can only delete players that have not participated in any rounds yet.</p>

<h2>Results</h2>

<table>
<tr>
<th>Round</th>
<th>Duration [s]</th>
<th>Competitors</th>
<th>crashed?</th>
<th>RX packets</th><th>TX packets</th><th>Packet loss</th>
<th>Payload</th>
<th></th><th></th>
</tr>
{% for result in result_list %}
<tr>

<td><a href="{% url "round" result.game.round.id %}">{{ result.game.round.id }}</a></td>

<td>{{ result.game.duration|floatformat:"1"}}</td>
<td>
<ol>
{% for result2 in result.game.playerresult_set.all %}
{% if result2 != result %}
<li>"{{ result2.player }}" by {{ result2.player.user }}</li>
{% endif %}
{% endfor %}
</ol>
</td>

<td>{% if result.crashed %}
Yes (<a href="{% url 'result' result.id %}">log</a>)
{% else %}
No
{% endif %}
</td>

<td>{{ result.received_packets }}</td>
<td>{{ result.transmit_packets }}</td>
<td>{{ result.get_packet_loss|floatformat:"1" }} %</td>
<td>{{ result.payload_bytes }} bytes</td>

<td>{% if result.timeline %}<a href="{{ result.timeline.url }}">player timeline</a>{% endif %}</td>
<td>{% if result.game.timeline %}<a href="{{ result.game.timeline.url }}">game timeline</a>{% endif %}</td>
</tr>
{% endfor %}
</table>

<h2>Code</h2>

<pre>
{{ player.code }}
</pre>

<a href="{% url 'user' %}">back</a>
{% endblock %}

web/front/templates/front/player_add.html
{% extends "base.html" %}

{% block title %}
Add a player
{% endblock %}

{% block content %}
<p><a href="https://github.com/avian2/spectrumwars/tree/master/examples">Examples</a></p>
<p><a href="https://spectrumwars.readthedocs.org/en/latest/transceiver.html">Documentation</a></p>

<form action="{% url 'player_add' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="submit"/>
</form>
{% endblock %}

web/front/templates/front/result.html
{% extends "base.html" %}

{% block title %}
Result {{ result.id }} for "{{ result.player }}" by {{ user }}
{% endblock %}

{% block content %}
<h2>Log</h2>

<pre>
{{ result.log }}
</pre>
{% endblock %}

web/front/templates/front/round.html
{% extends "base.html" %}

{% block title %}
Round {{ round.id }}
{% endblock %}

{% block content %}
<h2>Rankings</h2>

<h3>Most reliable</h3>

<table>
<tr>
<th>Name</th>
<th>Author</th>
<th>Worst packet loss</th>
<th>Avg. packet loss</th>
</tr>
{% for player in most_reliable %}
<tr>
<td>"{{ player }}"</td>
<td>{{ player.user }}</td>
<td>{% if player.max_packet_loss != None %}{{ player.max_packet_loss|floatformat:"1" }} %{% endif %}</td>
<td>{% if player.avg_packet_loss != None %}{{ player.avg_packet_loss|floatformat:"1" }} %{% endif %}</td>
</tr>
{% endfor %}
</table>

<h3>Fastest</h3>

<table>
<tr>
<th>Name</th>
<th>Author</th>
<th>Worst throughput</th>
<th>Avg. throughput</th>
</tr>
{% for player in fastest %}
<tr>
<td>"{{ player }}"</td>
<td>{{ player.user }}</td>
<td>{% if player.min_throughput != None %}{{ player.min_throughput|floatformat:"1" }} bytes/s{% endif %}</td>
<td>{% if player.avg_throughput != None %}{{ player.avg_throughput|floatformat:"1" }} bytes/s{% endif %}</td>
</tr>
{% endfor %}
</table>

<h3>Most cooperative</h3>

<table>
<tr>
<th>Name</th>
<th>Author</th>
<th>Coop. packet loss</th>
</tr>
{% for player in most_cooperative %}
<tr>
<td>"{{ player }}"</td>
<td>{{ player.user }}</td>
<td>{% if player.game_packet_loss != None %}{{ player.game_packet_loss|floatformat:"1" }} %{% endif %}</td>
</tr>
{% endfor %}
</table>

<h3>Best interferer</h3>

<table>
<tr>
<th>Name</th>
<th>Author</th>
<th>Packet loss of <br/>best competitor</th>
</tr>
{% for player in best_interferer %}
<tr>
<td>"{{ player }}"</td>
<td>{{ player.user }}</td>
<td>{% if player.other_packet_loss != None %}{{ player.other_packet_loss|floatformat:"1" }} %{% endif %}</td>
</tr>
{% endfor %}
</table>

<h2>Games</h2>

<table>
<tr>
<th>Players</th>
<th>Duration [s]</th>
<th></th>
</tr>
{% for game in game_list %}
<tr>
<td>
<ol>
{% for result in game.playerresult_set.all %}
<li>"{{ result.player }}" by {{ result.player.user}}</li>
{% endfor %}
</ol>
</td>
<td>{{ game.duration|floatformat:"1" }}</td>
<td>{% if game.timeline %}<a href="{{ game.timeline.url }}">timeline</a>{% endif %}</td>
</tr>
{% endfor %}
</table>


{% endblock %}

web/front/templates/front/rounds.html
{% extends "base.html" %}

{% block title %}
Spectrum Wars
{% endblock %}

{% block content %}

Currently ready to play: {{ player_num }} algorithms from {{ user_num }} users.

<h2>Rounds</h2>

<table>
<tr>
<th>id</th><th>start time</th><th>finish time</th><th>games played</th><th>players</th><th>per game</th><th>testbed</th><th>state</th><th></th>
{% for round in round_list %}
<tr>
<td>{{ round.id }}</a></td>
<td>{{ round.start_time }}</td>
<td>{% if round.finish_time %}{{ round.finish_time }}{% endif %}</td>
<td>{{ round.n_games }}</td>
<td>{{ round.n_players }}</td>
<td>{{ round.nplayers }}</td>
<td>{{ round.testbed }}</td>
<td>
{% if round.state == "started" %}
<span style="color: #0c0; font-weight: bold">{{ round.state }}</span>
{% elif round.state == "scheduled" %}
<span style="color: #ec0; font-weight: bold">{{ round.state }}</span>
{% else %}
{{ round.state }}
{% endif %}
</td>
<td>{% if round.state == "finished" %}<a href="{% url "round" round.id %}">results</a>{% endif %}</td>
</tr>
{% endfor %}
</table>

{% if user.is_authenticated %}
<p>Hello, {{ user }}!. <a href="{% url "user" %}">Your dashboard</a>.</p>
{% else %}
<p><a href="{% url "auth_login" %}">Log in</a></p>
{% endif %}

<p><a href="/admin">Admin</a></p>


<p><img src="{{ MEDIA_URL }}images/crew.png" style="margin-right: 40px"/><img src="{{ MEDIA_URL }}images/ijs.png" /></p>

{% endblock %}

web/front/templates/front/user.html
{% extends "base.html" %}

{% block title %}
Hello {{ user }}!
{% endblock %}

{% block content %}

<p>Your players:</p>

<table>
<tr>
<th>name</th><th>crash<br/>ratio</th><th>avg.<br>packet loss</th><th>created</th>
{% for player in player_list %}
<tr>
<td>
{% if player.enabled %}
<a href="{% url "player" player.id %}">{{ player.name }}</a>
{% else %}
<del><a href="{% url "player" player.id %}">{{ player.name }}</a></del>
{% endif %}
</td>
<td>{{ player.crash_ratio|floatformat:"0" }} %</td>
<td>{% if player.packet_loss != None %}{{ player.packet_loss|floatformat:"1" }} %{% endif %}</td>
<td>{{ player.created }}</td>
</tr>
{% endfor %}
</table>

<p>
<a href="{% url 'player_add' %}">Submit a player</a>
</p>
<p>
<a href="{% url 'rounds' %}">Back</a>
</p>
<p>
<a href="{% url 'auth_logout' %}">Log out</a>
</p>
{% endblock %}

web/templates/base.html
<html>
<head>
<body>
<h1>{% block title %}{% endblock %}</h1>

{% block content %}
{% endblock %}